# Generated by Django 5.2 on 2025-05-07 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('beauty', 'Beauty'), ('appliance', 'Appliance Repair')], max_length=50)),
                ('booking_fee', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
